streams:
    stable:
      type: production
    testing:
      type: production
    next:
      type: production
    testing-devel:
      type: development
      default: true
    next-devel:         # do not touch; line managed by `next-devel/manage.py`
      type: development # do not touch; line managed by `next-devel/manage.py`
    rawhide:
      type: mechanical
    # branched:
    #  type: mechanical
    # bodhi-updates:
    #   type: mechanical
    # bodhi-updates-testing:
    #   type: mechanical

additional_arches: []

#hotfix:
#  name: jlebon-test

source_config:
  url: https://github.com/coreos/fedora-coreos-config

# remove to disable S3 uploads
s3:
  bucket: prod-account-match-fcos-builds
  builds_key: "prod/streams/${STREAM}"

registry_repos:
  oscontainer: quay.io/fedora/fedora-coreos
  oscontainer_old: quay.io/coreos-assembler/fcos

default_artifacts:
  aarch64:
    - live
    - metal
    - metal4k
  ppc64le:
    - openstack
    - powervs
    - live
    - metal
    - metal4k
  s390x:
    - ibmcloud
    - openstack
    - live
    - metal
    - metal4k
  x86_64:
    - metal

# Temporary hack for AWS aarch64; see comment in `build-arch.Jenkinsfile`.
aws_aarch64_serial_console_hack: true

clouds:
  aws:
    # Accounts to share newly created AMIs with
    test_accounts:
      - "013116697141"
    bucket: prod-account-match-fcos-builds/ami-import
    primary_region: us-east-1
  azure:
    test_resource_group: fedora-coreos-testing
    test_storage_account: fedoracoreostesting
    test_storage_container: fedora-coreos-testing-image-blobs
  gcp:
    bucket: fedora-coreos-devel-image-uploads/image-import
    description: "Fedora, Fedora CoreOS Devel ${STREAM}, ${BUILDID}, ${BASEARCH} published on ${DATE}"
    family: "fedora-coreos-devel-${STREAM}"
    public: true
    licenses:
      - "https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"
