streams:
    testing-devel:
      type: development
      default: true

additional_arches: []

source_config:
  url: https://github.com/coreos/fedora-coreos-config

# remove to disable S3 uploads
s3_bucket: rhcos-jlebon

registry_repos:
  oscontainer: quay.io/jlebon/fedora-coreos
  oscontainer_old: quay.io/jlebon/fedora-coreos-2

default_artifacts:
  x86_64:
    - qemu
